/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinebookingsystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author corey
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    Statement st = null;
    
    public Registration() {
        initComponents();
       ConnectionManager conn = new ConnectionManager();
        conn.connectToDatabase();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        First_Name = new javax.swing.JTextField();
        Surname = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Phone_No = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        Password2 = new javax.swing.JTextField();
        FN_Label = new javax.swing.JLabel();
        SN_Lable = new javax.swing.JLabel();
        SN_Label = new javax.swing.JLabel();
        Add_Label = new javax.swing.JLabel();
        Em_Label = new javax.swing.JLabel();
        PH_label = new javax.swing.JLabel();
        PW = new javax.swing.JLabel();
        ConPw = new javax.swing.JLabel();
        ConfirmBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        First_Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        First_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                First_NameActionPerformed(evt);
            }
        });

        Surname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SurnameActionPerformed(evt);
            }
        });

        Address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Phone_No.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Password2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password2ActionPerformed(evt);
            }
        });

        FN_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FN_Label.setText("First Name");

        SN_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SN_Label.setText("Surname");

        Add_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Add_Label.setText("Address");

        Em_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Em_Label.setText("Email");

        PH_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PH_label.setText("Phone Number");

        PW.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PW.setText("Password");

        ConPw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ConPw.setText("Confirm Password");

        ConfirmBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ConfirmBtn.setText("Confirm");
        ConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtnActionPerformed(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBtn.setText("Back");

        Title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Title.setText("Registration Page");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FN_Label)
                            .addComponent(SN_Lable)
                            .addComponent(SN_Label)
                            .addComponent(Add_Label)
                            .addComponent(Em_Label)
                            .addComponent(PH_label)
                            .addComponent(PW)
                            .addComponent(ConPw))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Surname)
                            .addComponent(First_Name)
                            .addComponent(Address)
                            .addComponent(Email)
                            .addComponent(Phone_No)
                            .addComponent(Password)
                            .addComponent(Password2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BackBtn)
                        .addGap(18, 18, 18)))
                .addComponent(ConfirmBtn)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(Title)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Title)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FN_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SN_Lable)
                    .addComponent(SN_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Em_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Phone_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PH_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PW))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConPw))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmBtn)
                    .addComponent(BackBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void First_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_First_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_First_NameActionPerformed

    private void SurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SurnameActionPerformed

    private void Password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password2ActionPerformed

    private void ConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtnActionPerformed
        try{
            String query = "INSERT INTO dbflight.Registration( First_Name, Surname, Address, Email, Password, Phone_Number) values (?, ?, ?, ?, ?, ?,)";
         
            ps = conn.prepareStatement(query);
            ps.setString(1, First_Name.getText());
            ps.setString(2, Surname.getText());
            ps.setString(3, Address.getText());
            ps.setString(4, Email.getText());
            ps.setString(5, Password.getText());
            ps.setString(6, Phone_No.getText());
            ps.execute();
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.print("wrong");
        }
    }//GEN-LAST:event_ConfirmBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add_Label;
    private javax.swing.JTextField Address;
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel ConPw;
    private javax.swing.JButton ConfirmBtn;
    private javax.swing.JLabel Em_Label;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel FN_Label;
    private javax.swing.JTextField First_Name;
    private javax.swing.JLabel PH_label;
    private javax.swing.JLabel PW;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Password2;
    private javax.swing.JTextField Phone_No;
    private javax.swing.JLabel SN_Label;
    private javax.swing.JLabel SN_Lable;
    private javax.swing.JTextField Surname;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
